---
db_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIEMDCCApigAwIBAgIDJIEAMA0GCSqGSIb3DQEBDAUAMDoxODA2BgNVBAMMLzk4
  OTFhMjYyLTNhYWEtNGE1MS1iMjRhLTcyN2NhZTE4MjI0MyBQcm9qZWN0IENBMB4X
  DTE5MDQyNTEyMjI0N1oXDTI5MDQyMjEyMjI0N1owOjE4MDYGA1UEAwwvOTg5MWEy
  NjItM2FhYS00YTUxLWIyNGEtNzI3Y2FlMTgyMjQzIFByb2plY3QgQ0EwggGiMA0G
  CSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQC6o7nATsyTO2Q1vnJT8OeJWza9Gvwy
  tmY8OjCwP8ybCcfEAFskB7OEl7vE6HxbXo8TdBzNs0n7DHQMXywGrf2iot8vT6/5
  eq91F6iBumXywVa7IyQ05h/96wnwiTz/Uf+3jo1C0Upsfe75/U1J49e3JAvmb1NY
  Une5PDr8KpkECY4gpvyHXz2Is3odor7s4NPj4MYtXN7VNCpi292c1xauKlQdQP0L
  4UANVdA6nv7pdOkJJfj8+to8Csh/TDA883L03XFTzzLgIf/HYUYuRUD1CRq4+6NG
  x55RGiSQkuVEIdHDQlD6WxFKDZd/Ls2GN8EwAa5Sbn7DTZoT9gHm+yYyUpawxnJo
  Y2HYmVVCIABZGoeVIYBM64ckYyxu0Bhz8edNNWC4sRITbywHgrM10OjMcvsYLnlB
  zfagQ+KO2aF+xkRLRjulyz0290cJKXFab/BvzJyFDNYYTnI6OdFYuPmV75lVCJCt
  zsRt1hreNfL+wPudFPcMElFp/w4vdkn0Sk8CAwEAAaM/MD0wHQYDVR0OBBYEFMVW
  v9/oA1ic5wP/+l1Zoku/AhZdMA8GA1UdEwQIMAYBAf8CAQAwCwYDVR0PBAQDAgEG
  MA0GCSqGSIb3DQEBDAUAA4IBgQC04RXoLJHg8sUjBClwiHgIoDueoKD9MUtleNZB
  rUFkdnKp1+J2HXEj0Q2FEQGD8yfQxiTE1Z6U+wrQtwYq6tnGW7sP6Fhs4sInK01F
  YgWcF+KLOZcSyORnTHujOMpebYLjX3BUOveIqVT4aJu8/lFwG8LmJZLurxIb3Rkb
  Key1emu7hTEpTj/MmZ8W2/yCDs+CmNpMnlTUvS1hWeFz203mP+/trj6bQxTkOPZp
  VTMFbZJbUVAs4mSoKs2QC6mWtgjzgEE2FCQvYUVLhuudEwURYQLCVMTm/TromnuW
  fnnSS3bGppIJylX8TPQDymmM/yP8GTacvSvLMC347CMnW4DCqYHtgmhkjwH4cofr
  Y81vLkfl2KT0RDSVrHw+0VKQaJo/i2PwvTQlUYcUmlAqS2X+k5YghZIRo19VXIMq
  5U0115UPrUPPvXEDXdYWrptrYavDl9UK82H/S2wPcmYzrYl/8fjthIKKkg++dKGD
  8V9oYuuqaXheQtNhOxS/KGGlArU=
  -----END CERTIFICATE-----
